spring.application.name=ollama-spring-poc

spring.datasource.url=jdbc:mysql://localhost:3306/ollama_poc?useUnicode=true&characterEncoding=UTF-8
spring.datasource.username=pocuser
spring.datasource.password=pocpass

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
